image: cirrusci/flutter:latest

stages:
  - build
  - test
  - deploy

before_script:
  - flutter doctor
  - flutter pub get

build-job:
  stage: build
  script:
    - flutter build apk --release

unit-test-job:
  stage: test
  script:
    - flutter test

lint-test-job:
  stage: test
  script:
    - flutter analyze

deploy-job:
  stage: deploy
  environment: production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
